export enum GameEvent {
    NewGame = "new-game",
    LoadGame = "load-game",
    GameLoaded = "game-loaded",
    SetTimeSpeed = "set-time-speed",
    SetTime = "set-time",
    SetWeather = "set-weather",
    SelectionChanged = "selection-changed",
    StoryEventEnded = "StoryEventEnded",
    StoryEventOptionChosen = "StoryEventOptionChosen",
    StoryEventStarted = "StoryEventStarted",
    StoryEventPageChanged = "StoryEventPageChanged",
    ViewsInitialized = "ViewsInitialized",
    ResourcesUpdated = "ResourcesUpdated",
}
